Obsolete error message
As i can see, this hook was renamed from 'delete' to 'discard', and the error message forming name still have it's old value.
I'm getting this trace:

    error:  Error: The 'delete' hook can only be used on the '["create","update","patch"]' service method(s).
        at exports.default (/home/aquajet/projects/mfo/api/node_modules/feathers-hooks-common/lib/services/check-context.js:24:11)
        at exports.default (/home/aquajet/projects/mfo/api/node_modules/feathers-hooks-common/lib/services/check-context-if.js:9:32)
        at Object.<anonymous> (/home/aquajet/projects/mfo/api/node_modules/feathers-hooks-common/lib/services/discard.js:13:34)